config/routes.rb
Rails.application.routes.draw do
  
  get 'bought_movies(.format)', to: 'bought_movies#index', as: 'bought_movies'
  post 'movies/buy', to: 'movies#buy'

  root to: 'movies#index'

  devise_for :users , controllers: { confirmations: "users/confirmations", passwords: "users/passwords", registrations: "users/registrations", sessions: "users/sessions", unlocks: "users/unlocks" }

end

app/models/bought_movie.rb
class BoughtMovie < ActiveRecord::Base

  belongs_to :user

  validates :title, presence: true
  validates :movie_id, presence: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true

  has_many :bought_movies



  def buy_movie (movie_params)
    self.bought_movies.create! movie_params
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bought_movies_controller.rb
class BoughtMoviesController < ApplicationController
  before_action :set_bought_movie, only: [:show, :edit, :update, :destroy]

  # GET /bought_movies
  # GET /bought_movies.json
  def index
    @bought_movies = current_user.bought_movies.all
  end

  # GET /bought_movies/1
  # GET /bought_movies/1.json
  def show
  end


  # DELETE /bought_movies/1
  # DELETE /bought_movies/1.json
  def destroy
    @bought_movie.destroy
    respond_to do |format|
      format.html { redirect_to bought_movies_url, notice: 'bought movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bought_movie
      @bought_movie = boughtMovie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bought_movie_params
      params.require(:bought_movie).permit(:id, :title, :poster_url)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
  end


  def buy
    @bought_movie = current_user.buy_movie movie_params
    respond_to do |format|
      if @bought_movie
        format.json { render json: {}, status: :created }
      else
        format.json { render json: {}, status: :unprocessable_entity }
      end
    end
  end
  

  private


  # Never trust parameters from the scary internet, only allow the white list through.
  def movie_params
    params.require(:movie).permit(:movie_id, :title, :poster_url)
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
    def configure_sign_up_params
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit :name, :email, :password, :password_confirmation }
    end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bought_movies_helper.rb
module BoughtMoviesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bought_movies/_form.html.erb
<%= form_for(@bought_movie) do |f| %>
  <% if @bought_movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bought_movie.errors.count, "error") %> prohibited this bought_movie from being saved:</h2>

      <ul>
      <% @bought_movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :integer %><br>
    <%= f.text_field :integer %>
  </div>
  <div class="field">
    <%= f.label :integer %><br>
    <%= f.text_field :integer %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bought_movies/edit.html.erb
<h1>Editing bought Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @bought_movie %> |
<%= link_to 'Back', bought_movies_path %>

app/views/bought_movies/index.html.erb
<div class="container">


  <div class="header">
    <h2>Library</h2>
  </div>

  <% @bought_movies.each do |bought_movie| %>
    <div class="row">
      <div class="six columns">
        <%= bought_movie.title %>
      </div>
      <div class="four columns">
        <img src="<%= bought_movie.poster_url -%>" alt="<%= bought_movie.title -%>" />
      </div>
    </div>
  <% end %>    


</div>

app/views/bought_movies/new.html.erb
<h1>New bought Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', bought_movies_path %>

app/views/bought_movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Integer:</strong>
  <%= @bought_movie.integer %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @bought_movie.integer %>
</p>

<p>
  <strong>String:</strong>
  <%= @bought_movie.string %>
</p>

<p>
  <strong>String:</strong>
  <%= @bought_movie.string %>
</p>

<%= link_to 'Edit', edit_bought_movie_path(@bought_movie) %> |
<%= link_to 'Back', bought_movies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VideoRental</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



  <div class="user_bar container">
    <% if user_signed_in? %>
      
      <span>Loged in as <%= current_user.name -%></span>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
      <%= link_to('Library', bought_movies_path) %>
    <% else %>
      
      <%= link_to('Login', new_user_session_path)  %>  
      
    <% end %>

    <%= link_to 'Home', root_path %>
  </div>



  <% unless flash.empty? %>
    <div class="flash-notices container">
      
      <% flash.each do |key, value| %>
        <div class="<%= key %>"><%= value %></div>
      <% end %>

    </div>
  <% end %>



  <%= yield %>



  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>



</body>
</html>

app/views/movies/index.html.erb
<section class="search_box container">
  <div class="row">
    <input type="text" class="u-full-width" placeholder="Search for movies" data-widget="movie-search" data-target="movie_index" />
  </div>
</section>


<section id="movie_index" class="movie_index container" data-widget="movie-index">
</section>


<script id="movie_widget_template" type="text/x-handlebars-template">
  <article class="movie_widget row" data-widget="movie-widget">

    <div class="four columns">
      <header>{{title}}</header>
      <img src="{{posters.thumbnail}}" alt="{{title}}"/>
    </div>
    <aside class="details eight columns">
      <p class="year">Year: {{year}}</p>
      <p class="rating">Rating: {{mpaa_rating}}</p>
      <p class="runtime">Runtime: {{runtime}} minutes</p>
      <p class="synopsis">{{synopsis}}</p>
      <% if user_signed_in? %>
        {{#ifInBoughtList id}}
          <button class="buy_movie_button button-primary" disabled="disabled">IN LIBRARY</button>
        {{else}}
          <button class="buy_movie_button button-primary" >BUY €2.99</button>
        {{/ifInBoughtList}}
      <% else %>
        <button class="show_login_button button-primary">BUY</button>
        <aside class="login_advertise" style="display:none">
          You have to <a href="/users/sign_in">login</a> to buy movies.
        </aside>
      <% end %>
    </aside>
  </article>
</script>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>